# Generated by Django 3.2.9 on 2022-03-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=15)),
                ('lastName', models.CharField(max_length=15)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')])),
                ('phone', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=100)),
                ('dateOfBirth', models.DateTimeField()),
                ('profileLink', models.CharField(max_length=245)),
                ('interest', models.JSONField()),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
                ('deletedAt', models.DateTimeField()),
            ],
        ),
    ]
