# Generated by Django 3.2.9 on 2022-03-09 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20220309_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='isGlobal',
            field=models.CharField(db_column='global', max_length=2),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='userId',
            field=models.ForeignKey(blank=True, db_column='userId', null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.user', verbose_name='User'),
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('likes', models.IntegerField()),
                ('disLikes', models.IntegerField()),
                ('superLikes', models.IntegerField()),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
                ('deletedAt', models.DateTimeField()),
                ('fromUserId', models.ForeignKey(blank=True, db_column='fromUserId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fromUserId', to='dashboard.user', verbose_name='From User')),
                ('toUserId', models.ForeignKey(blank=True, db_column='toUserId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toUserId', to='dashboard.user', verbose_name='To User')),
            ],
            options={
                'verbose_name_plural': 'User Rating',
                'db_table': 'user_Rating',
            },
        ),
        migrations.CreateModel(
            name='ProfileSetting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photosLink', models.JSONField()),
                ('aboutMe', models.CharField(max_length=225)),
                ('passion', models.CharField(max_length=45)),
                ('jobTitle', models.CharField(max_length=45)),
                ('company', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=45)),
                ('interested', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')])),
                ('showGender', models.CharField(max_length=5)),
                ('showAge', models.CharField(max_length=5)),
                ('showDistance', models.CharField(max_length=5)),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
                ('deletedAt', models.DateTimeField()),
                ('userId', models.ForeignKey(blank=True, db_column='userId', null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.user', verbose_name='User')),
            ],
        ),
    ]
