# Generated by Django 3.2.9 on 2022-03-09 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20220309_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('description', models.JSONField()),
                ('price', models.CharField(max_length=15)),
                ('tingler', models.IntegerField()),
                ('createdAt', models.DateTimeField()),
                ('deletedAt', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Plan',
                'db_table': 'plan',
            },
        ),
        migrations.CreateModel(
            name='PlanSubscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('paymentMethod', models.CharField(max_length=5)),
                ('createdAt', models.DateTimeField()),
                ('planId', models.ForeignKey(blank=True, db_column='planId', null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.plan')),
                ('userId', models.ForeignKey(blank=True, db_column='userId', null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.user')),
            ],
        ),
    ]
