# Generated by Django 3.2.9 on 2022-03-09 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_plan_plansubscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plansubscription',
            options={'verbose_name_plural': 'Plan Subscription'},
        ),
        migrations.AlterModelTable(
            name='plansubscription',
            table='plan_subscription',
        ),
    ]
